site_name: Clubfoot Resources for Adults
theme:
  #logo: assets/mazda-logo-512-white.png
  #favicon: assets/mazda-logo-512-white.ico
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - toc.integrate
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.top
    - search.suggest
    - search.highlight
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Home: index.md
  - Financial Resources: funding.md
  - Medical Practitioners:
    - Introduction: practitioners/index.md
    - Pedorthist: practitioners/pedorthist.md
    - Physiotherapist: practitioners/physiotherapist.md
    - Podiotrist: practitioners/podiatist.md
    - Orthotist: practitioners/orthotist.md
    - Occupational Therapist: practitioners/occupationaltherapist.md
    - Social Worker: practitioners/socialworker.md
  - Guides:
    - Home: guides/index.md
    - guides/how-to-dtc.md
  - Support: support.md
  - Other Resources: otherresources.md

